"""Build five paired, unlisted article drafts from reviewed editorial copy."""
import html
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BASE = "https://stavroslitsos.com/"
DATE = "2026-09-19"

# Bibliography verified against NCBI PubMed on 2026-09-19. IDs are stable links.
REFS = {
 "shoulder": [
 ("Ricci V et al.", "Clinical/Sonographic Assessment and Management of Calcific Tendinopathy of the Shoulder: A Narrative Review", "Diagnostics", 2022, 36553104),
 ("Saran S et al.", "Imaging of calcific tendinopathy: natural history, migration patterns, pitfalls, and management: a review", "British Journal of Radiology", 2024, 38346707),
 ("Moosmayer S et al.", "Ultrasound guided lavage with corticosteroid injection versus sham lavage with and without corticosteroid injection for calcific tendinopathy of shoulder: randomised double blinded multi-arm study", "BMJ", 2023, 37821122),
 ("Pieber K et al.", "Long-Term Course of Shoulders After Ultrasound Therapy for Calcific Tendinitis: Results of the 10-Year Follow-Up of a Randomized Controlled Trial", "American Journal of Physical Medicine & Rehabilitation", 2018, 29613883),
 ("Brindisino F et al.", "The effectiveness of extracorporeal shock wave therapy for rotator cuff calcific tendinopathy. A systematic review with meta-analysis", "Physiotherapy Research International", 2024, 38878302),
 ("Kvalvaag E et al.", "Effectiveness of Radial Extracorporeal Shock Wave Therapy (rESWT) When Combined With Supervised Exercises in Patients With Subacromial Shoulder Pain: A Double-Masked, Randomized, Sham-Controlled Trial", "American Journal of Sports Medicine", 2017, 28586628)],
 "rapid": [
 ("Driban JB et al.", "Risk factors and the natural history of accelerated knee osteoarthritis: a narrative review", "BMC Musculoskeletal Disorders", 2020, 32471412),
 ("Foreman SC et al.", "Meniscal Root Tears and Extrusion Are Significantly Associated with the Development of Accelerated Knee Osteoarthritis: Data from the Osteoarthritis Initiative", "Cartilage", 2021, 32567341),
 ("Driban JB et al.", "Accelerated Knee Osteoarthritis Is Characterized by Destabilizing Meniscal Tears and Preradiographic Structural Disease Burden", "Arthritis & Rheumatology", 2019, 30592385),
 ("Roemer FW et al.", "Change in MRI-detected subchondral bone marrow lesions is associated with cartilage loss: the MOST Study", "Annals of the Rheumatic Diseases", 2009, 18829615),
 ("Driban JB et al.", "Risk factors can classify individuals who develop accelerated knee osteoarthritis: Data from the osteoarthritis initiative", "Journal of Orthopaedic Research", 2018, 28776751),
 ("NICE", "Osteoarthritis in over 16s: diagnosis and management, NG226", "Guideline", 2022, "https://www.nice.org.uk/guidance/ng226/chapter/recommendations")],
 "pain": [
 ("Batchelor V et al.", "Peripheral neuronal sensitization and neurovascular remodelling in osteoarthritis pain", "Nature Reviews Rheumatology", 2025, 40796685),
 ("Wang X et al.", "Synovitis mediates the association between bone marrow lesions and knee pain in osteoarthritis", "Osteoarthritis and Cartilage", 2022, 35750239),
 ("Felson DT et al.", "The association of bone marrow lesions with pain in knee osteoarthritis", "Annals of Internal Medicine", 2001, 11281736),
 ("Hill CL et al.", "Synovitis detected on magnetic resonance imaging and its relation to pain and cartilage loss in knee osteoarthritis", "Annals of the Rheumatic Diseases", 2007, 17491096),
 ("Magnusson K et al.", "Relationship Between Magnetic Resonance Imaging Features and Knee Pain Over Six Years in Knees Without Radiographic Osteoarthritis at Baseline", "Arthritis Care & Research", 2021, 32741084),
 ("Guermazi A et al.", "Prevalence of abnormalities in knees detected by MRI in adults without knee osteoarthritis: population based observational study", "BMJ", 2012, "https://doi.org/10.1136/bmj.e5339")],
 "injection": [
 ("NICE", "Osteoarthritis in over 16s: diagnosis and management, NG226", "Guideline", 2022, "https://www.nice.org.uk/guidance/ng226/chapter/recommendations"),
 ("Kasitinon D et al.", "Accuracy and Efficacy of Intra-articular Knee Injections/Aspirations Under Ultrasound Versus Landmark Guidance: A Systematic Review", "American Journal of Physical Medicine & Rehabilitation", 2026, 40729535),
 ("Di Sante L et al.", "Ultrasound guided injection of a painful knee osteoarthritis with medial meniscus extrusion: a case series study", "Muscles, Ligaments and Tendons Journal", 2017, 29264345),
 ("Coll C et al.", "Ultrasound-Guided Perimeniscal Injections: Anatomical Description and Feasibility Study", "Journal of Ultrasound in Medicine", 2022, 33788316),
 ("McAlindon TE et al.", "Effect of Intra-articular Triamcinolone vs Saline on Knee Cartilage Volume and Pain in Patients With Knee Osteoarthritis: A Randomized Clinical Trial", "JAMA", 2017, 28510679),
 ("Noorduyn JCA et al.", "Effect of Physical Therapy vs Arthroscopic Partial Meniscectomy in People With Degenerative Meniscal Tears: Five-Year Follow-up of the ESCAPE Randomized Clinical Trial", "JAMA Network Open", 2022, 35802374)],
 "sitting": [
 ("Kizaki K et al.", "Deep gluteal syndrome is defined as a non-discogenic sciatic nerve disorder with entrapment in the deep gluteal space: a systematic review", "Knee Surgery, Sports Traumatology, Arthroscopy", 2020, 32246173),
 ("De Smet AA et al.", "MRI appearance of the proximal hamstring tendons in patients with and without symptomatic proximal hamstring tendinopathy", "AJR American Journal of Roentgenology", 2012, 22268187),
 ("Hopayian K et al.", "Four symptoms define the piriformis syndrome: an updated systematic review of its clinical features", "European Journal of Orthopaedic Surgery & Traumatology", 2018, 28836092),
 ("Mellor R et al.", "Education plus exercise versus corticosteroid injection use versus a wait and see approach on global outcome and pain from gluteal tendinopathy", "BMJ", 2018, 29720374),
 ("Boonstra AM et al.", "Cut-Off Points for Mild, Moderate, and Severe Pain on the Numeric Rating Scale for Pain in Patients with Chronic Musculoskeletal Pain", "Frontiers in Psychology", 2016, 27746750),
 ("Rich A et al.", "Treatment of Proximal Hamstring Tendinopathy with Individualized Physiotherapy: A Clinical Commentary", "International Journal of Sports Physical Therapy", 2025, 40469642)]
}

# Every section is independently written for the site, not a transcript translation.
ARTICLES = [
 dict(key="shoulder", video="1VWGxoZwoR8", no_slug="kalk-i-skuldersenen-ultralyd-behandling", en_slug="shoulder-calcific-tendinopathy-ultrasound-treatment", image=20,
 no=dict(title="Kalk i skuldersenen – hva betyr funnet for behandlingen?", desc="Kalk i rotatorcuffen er en dynamisk tilstand. Ultralydfunn må ses sammen med smerte, funksjon og usikker behandlingseffekt.", alt="Illustrasjon av en liten kalkavleiring nær skuldersenens feste", tags=["Skulder", "Kalktendinopati", "Ultralyd", "Behandling"], intro="En kalkavleiring i en skuldersene kan se dramatisk ut på bildet, men størrelsen eller plasseringen forteller ikke alene hvorfor skulderen gjør vondt. Forløpet kan endre seg, og behandling bør velges etter kliniske plager – ikke bare etter et hvitt punkt på ultralyd.", sections=[
 ("Hva er kalktendinopati?", ["Tilstanden innebærer avleiring av kalsiumholdig materiale i eller omkring rotatorcuffens sener. Beskrivende faser for dannelse, hvile og oppløsning brukes i litteraturen, men et enkelt bilde kan ikke med sikkerhet fortelle nøyaktig hvor en person er i et biologisk forløp. Ultralyd kan vise avleiringens konsistens og om den ligger i senen, nær slimposen eller i omkringliggende vev.", "Smerte kan komme gradvis eller plutselig. Når en avleiring brytes ned og irriterer omkringliggende vev, kan skulderen bli svært øm. En avleiring kan også være til stede uten tilsvarende symptomer. Derfor må bevegelse, belastning, søvnplager og andre mulige skulderdiagnoser vurderes samtidig."]),
 ("Hva kan videoens teori forklare?", ["Videoen foreslår at kalk først dannes ved senefestet mot beinet, og at senere bilder kan vise materiale som har flyttet seg. Det er en interessant mekanistisk hypotese, men den er ikke etablert som en generell forklaring for alle kalkavleiringer. Bildediagnostiske oversikter beskriver flere mulige mønstre for migrasjon; de beviser ikke hvor hver enkelt avleiring opprinnelig oppstod.", "Skillet mellom en kompakt avleiring og mer spredt materiale kan være nyttig når man diskuterer funn, men gir ikke i seg selv et validert behandlingsskjema. Det ville være for skråsikkert å love at én bestemt nåleteknikk hjelper i den ene fasen og skader i den andre."]),
 ("Hva vet vi om behandling?", ["Tilpasset aktivitet, smertelindring og gradvis gjenopptrening er ofte første steg. Trykkbølgebehandling kan hjelpe noen, men systematiske oversikter viser usikkerhet og variasjon mellom studiene. En randomisert studie fant ingen generell tilleggseffekt av radial trykkbølgebehandling til veiledet trening ved subakromiale smerter, men en forhåndsdefinert undergruppe med kalk hadde mulig nytte.", "Ultralydveiledet skylling av kalk er heller ikke et sikkert svar for alle: en norsk-svensk, placebokontrollert BMJ-studie med 220 deltakere fant ingen fordel av skylling med kortison sammenlignet med placebobehandling over studiens oppfølging. Andre studier og oppsummeringer har gitt ulike resultater. Derfor bør forventet gevinst, ulemper, naturlig forløp og pasientens mål drøftes før et inngrep."]),
 ("Når bør skulderen vurderes på nytt?", ["Ved vedvarende betydelige smerter, tydelig krafttap, feber eller en ny skade bør diagnosen og planen vurderes på nytt. Det viktige er ikke å «fjerne kalken for enhver pris», men å forklare funnet presist og følge smerte og funksjon over tid. Langtidsoppfølging viser at mange avleiringer kan forsvinne, uten at forsvinningen nødvendigvis er selve forklaringen på bedring."])], box="Jeg kombinerer sykehistorie, klinisk undersøkelse og målrettet ultralyd når det er relevant. Jeg forklarer hva avleiringen viser – og hva bildet ikke kan avgjøre – før vi velger en plan som tar hensyn til funksjon og pasientens ønsker."),
 en=dict(title="Shoulder Calcium Deposits – What Do They Mean for Treatment?", desc="Calcific rotator cuff tendinopathy changes over time. Ultrasound findings need to be interpreted alongside symptoms, function and treatment uncertainty.", alt="Illustration of a small calcium deposit near a rotator cuff tendon attachment", tags=["Shoulder", "Calcific tendinopathy", "Ultrasound", "Treatment"], intro="A calcium deposit in a shoulder tendon may look striking on a scan, but its size or position alone cannot explain why a shoulder hurts. The condition can evolve, so treatment decisions should follow the clinical picture rather than an isolated bright spot on ultrasound.", sections=[
 ("What is calcific tendinopathy?", ["Calcium-containing material accumulates in or around a rotator cuff tendon. Formation, resting and resorptive phases are useful descriptions in the literature, but a single scan cannot establish an exact biological stage for an individual. Ultrasound can help assess the deposit's appearance and whether it lies within the tendon, near the bursa or in surrounding tissue.", "Pain may develop gradually or abruptly. A deposit that is breaking down can irritate nearby tissue and cause severe symptoms. Deposits may also be present without proportional pain. Movement, loading, sleep disturbance and alternative shoulder diagnoses therefore matter as well."]),
 ("A plausible theory is not yet a treatment rule", ["The video suggests that deposits originate near the tendon–bone attachment and later migrate. This is an interesting mechanistic hypothesis, not an established explanation for every deposit. Imaging reviews describe several migration patterns without proving the origin of a particular patient's calcification.", "Distinguishing a compact deposit from dispersed material can inform discussion, but it does not provide a validated algorithm that says one needle technique helps in one stage and harms in another. Such precise promises would exceed the evidence."]),
 ("What about treatment?", ["Appropriately adjusted activity, symptom relief and progressive rehabilitation often come first. Shockwave therapy may help some patients, although systematic reviews report heterogeneous studies and uncertainty. One sham-controlled trial found no overall added benefit of radial shockwaves alongside supervised exercise for subacromial pain; a prespecified calcification subgroup showed a possible benefit.", "Ultrasound-guided lavage is not a guaranteed solution either. A Norwegian–Swedish sham-controlled BMJ trial involving 220 adults found no advantage of lavage with corticosteroid over sham treatment during follow-up. Other studies and syntheses have produced differing results. Expected benefit, possible downsides, natural history and the patient's goals should be discussed before an invasive procedure."]),
 ("When to reassess", ["Persistent substantial pain, marked weakness, fever or a new injury warrants reassessment of the diagnosis and plan. The aim is not to remove calcium at any cost, but to explain the finding accurately and track pain and function over time. In long-term follow-up many deposits resolved, without resolution necessarily explaining recovery."])], box="I bring together the history, a clinical examination and focused ultrasound when appropriate. I explain what the deposit shows – and what imaging cannot establish – before agreeing a plan centred on function and the patient's goals.")),
 dict(key="rapid", video="0tStvw0ZSu0", no_slug="hvorfor-utvikler-noen-kneartrose-raskt", en_slug="why-some-knees-develop-osteoarthritis-faster", image=21,
 no=dict(title="Hvorfor utvikler noen knær artrose raskere?", desc="Rask utvikling av kneartrose er mer sammensatt enn slitasje og viljestyrke. Risiko, menisk, bein og symptomer må vurderes sammen.", alt="Illustrasjon som sammenligner ulike grader av forandringer i kneledd", tags=["Kneartrose", "Menisk", "Risikofaktorer", "Rehabilitering"], intro="To personer med tilsynelatende like kneplager kan få svært ulike forløp. Det skyldes ikke bare hvor godt de «tar vare på kneet». Alder, tidligere skade, kroppsvekt, leddets belastningsforhold og skader i menisk eller beinet under brusken kan spille inn.", sections=[
 ("Hva betyr «rask utvikling»?", ["Forskere bruker begrepet akselerert kneartrose om personer som går fra ingen tydelig artrose på røntgen til langtkommen radiografisk artrose i løpet av få år. Det er en definisjon brukt i studier, ikke en etikett man kan sette etter én vond uke. En oversikt over Osteoarthritis Initiative anslår at minst én av sju med nytilkommet røntgenartrose kan følge et slikt raskt forløp.", "Plutselige symptomer betyr heller ikke automatisk rask strukturell forverring. Smerte og røntgenfunn utvikler seg ikke alltid parallelt. Derfor trengs sykehistorie, funksjonsvurdering og eventuelt målrettet bildediagnostikk når bildet ikke passer med symptomene."]),
 ("Mer enn en «reserve som er brukt opp»", ["Videoen beskriver et kne som passerer en belastningsterskel. Som bilde på sårbarhet kan det være forståelig, men det er ikke en dokumentert biologisk måling av «reserve». Observasjonsstudier knytter akselerert artrose til blant annet høyere alder, kroppsmasseindeks, feilstilling, eksisterende vevsforandringer og nye leddskader. Meniskrotrifter og menisk som glir ut fra sin normale posisjon er spesielt relevante funn i noen forløp.", "MR-studier viser også at forandringer i beinet under brusken kan variere over tid og henge sammen med senere brusktap. Slike assosiasjoner sier noe om risiko i grupper; de er ikke en individuell spådom og betyr ikke at hver meniskskade ender i rask artrose."]),
 ("Hva kan du faktisk påvirke?", ["Regelmessig, tilpasset aktivitet og styrketrening er grunnleggende tiltak ved kneartrose. Å balansere belastning og restitusjon er fornuftig, men å påstå at utilstrekkelig «selvomsorg» er årsaken til et raskt forløp kan legge urimelig skyld på pasienten. En ny skade eller et betydelig funksjonsfall krever vurdering fremfor bare et generelt råd om å bevege seg mer.", "NICE anbefaler en klinisk artrosediagnose ved typiske plager og fraråder rutinemessig bildediagnostikk når den ikke vil endre håndteringen. Ved atypiske eller plutselig alvorlige plager må andre årsaker vurderes. Informasjon om usikkerhet gjør det lettere å velge hensiktsmessig aktivitet uten å skape unødig frykt."])], box="Jeg vurderer endring i symptomer, belastningsevne og kliniske funn, ikke bare en røntgengrad. Planen skal være tilpasset den enkelte og justeres når forløpet avviker fra det vi forventer."),
 en=dict(title="Why Do Some Knees Develop Osteoarthritis Faster?", desc="Rapid knee osteoarthritis progression is more complex than wear and self-care: joint injury, risk factors and clinical change matter.", alt="Illustration comparing different degrees of change in knee joints", tags=["Knee osteoarthritis", "Meniscus", "Risk factors", "Rehabilitation"], intro="Two people with apparently similar knee symptoms can follow very different paths. It is not simply a question of how well they look after their knees. Age, previous injury, body weight, joint loading and changes in the meniscus or bone beneath the cartilage may all contribute.", sections=[
 ("What does rapid progression mean?", ["Researchers use accelerated knee osteoarthritis for progression from no clear radiographic disease to advanced radiographic osteoarthritis over a few years. It is a study definition, not a label to apply after one painful week. A review of Osteoarthritis Initiative data estimated that at least one in seven people with incident radiographic osteoarthritis followed this faster trajectory.", "Sudden pain does not automatically mean rapid structural deterioration. Symptoms and radiographic findings do not always move together. The history, function and targeted imaging when clinically indicated can clarify an unusual course."]),
 ("More than a depleted 'reserve'", ["The video uses the idea of a knee passing a load threshold. This may be a helpful metaphor, but it is not a measured biological 'reserve'. Observational studies link accelerated disease with older age, higher body mass index, alignment, existing tissue changes and new joint injury. Root tears and displacement of the meniscus are particularly relevant in some cases.", "MRI studies also show that changes in bone beneath cartilage can vary over time and be associated with subsequent cartilage loss. These are group-level associations, not a prediction for an individual or proof that every meniscal lesion will cause rapid osteoarthritis."]),
 ("What can be changed?", ["Regular, adapted activity and strengthening are central to osteoarthritis care. Balancing load and recovery is sensible, but blaming rapid progression on inadequate 'self-care' oversimplifies the evidence and unfairly burdens patients. New injury or a marked loss of function deserves assessment rather than a generic instruction to move more.", "NICE recommends clinical diagnosis for typical osteoarthritis and advises against routine imaging when it would not change care. Atypical or suddenly severe symptoms should prompt consideration of alternative causes. Honest communication about uncertainty can support appropriate activity without unnecessary fear."])], box="I look at changes in symptoms, weight-bearing ability and examination findings, not an X-ray grade alone. The plan is individual and should be reconsidered if the course differs from what we expected.")),
 dict(key="pain", video="NO-aZeXH3mc", no_slug="bruskslitasje-og-knesmerter", en_slug="cartilage-wear-and-knee-pain", image=22,
 no=dict(title="Bruskslitasje og knesmerter – hvorfor er ikke bildet hele svaret?", desc="Leddbrusken er normalt uten smertefibre, men kneartrose involverer flere vev. MR-funn og smerter må tolkes med varsomhet.", alt="Illustrasjon av brusk, bein under brusken og leddhinne i et kneledd", tags=["Knesmerter", "Brusk", "MR", "Smerteforståelse"], intro="Å høre at brusken i kneet er «slitt ned» kan gjøre deg bekymret for at smertene bare vil øke. Det er ikke slik det nødvendigvis fungerer. Et kne er et helt organ, og sammenhengen mellom bildet, vevene og opplevd smerte er sammensatt.", sections=[
 ("Hvis brusken ikke har nerver, hva gjør vondt?", ["Frisk leddbrusk har normalt ikke smertefibre som sender smertesignaler. Men leddhinne, bein under brusken, leddkapsel, leddbånd og deler av menisken har nerveforsyning. Ved artrose kan også nervevekst og økt følsomhet endre hvordan belastning og betennelsessignaler oppleves. Det betyr ikke at bruskforandringer er irrelevante: de kan påvirke belastningsfordeling og vev rundt seg.", "Studier knytter forandringer i beinmargen under brusken og betennelsesforandringer i leddhinnen til knesmerter. En longitudinell studie fant at endringer i leddhinnen fulgte endringer i smerte, og en annen fant sammenheng mellom økende beinmargsforandringer og nye plager. Likevel varierer styrken på sammenhengen mellom studier og grupper."]),
 ("Hvorfor kan MR ikke fortelle alt?", ["MR beskriver struktur, ikke hvordan hjernen opplever smerte. I en BMJ-studie av personer over 50 med normalt artroserøntgen var bruskforandringer vanlig også uten smerter. En seksårig oppfølging av knær uten røntgenartrose fant enkelte statistiske sammenhenger mellom MR-funn og smerte, men ingen enkeltfunn ga en klinisk viktig forskjell i knesmerte. Det er derfor for enkelt å kalle ett MR-funn «årsaken» hos enhver pasient.", "Videoens budskap om at brusken ikke selv har normal smerteinnervasjon er godt begrunnet. Derimot er påstanden om én universelt sterkeste MR-markør for smerte for bastant. Type plage, stadium, andre vev og individuell smertefølsomhet påvirker hva som er relevant."]),
 ("Hva betyr dette for behandling?", ["Det er ikke nødvendig å «reparere et bilde» før noen kan bli bedre. Kartlegg når smerten kommer, hva som provoserer, hevelse, funksjon og hva som er viktig i hverdagen. Ved typisk artrose er informasjon, tilpasset aktivitet og styrketrening sentrale tiltak. Ved akutt kraftig endring, traume eller uvanlige symptomer må diagnosen vurderes på nytt.", "En forståelig forklaring på hva bildene viser – og ikke viser – kan redusere både falsk trygghet og unødvendig alarm. Smerte er reell også når bildene virker beskjedne."])], box="Jeg tar smerten på alvor uten å gjøre én MR-observasjon til en sikker forklaring. Vi knytter symptomer, klinisk undersøkelse og eventuelle bilder til et konkret mål for funksjon."),
 en=dict(title="Cartilage Wear and Knee Pain – Why Imaging Is Not the Whole Answer", desc="Normal cartilage lacks pain fibres, but knee osteoarthritis involves several tissues. MRI findings and pain require careful interpretation.", alt="Illustration of cartilage, underlying bone and joint lining in a knee", tags=["Knee pain", "Cartilage", "MRI", "Pain science"], intro="Being told that the cartilage in your knee is 'worn out' can make worsening pain seem inevitable. It is not. A knee is a whole organ, and the relationship between imaging, tissues and experienced pain is complex.", sections=[
 ("If cartilage lacks nerves, what hurts?", ["Healthy articular cartilage normally has no pain fibres. The joint lining, underlying bone, capsule, ligaments and parts of the meniscus do have sensory innervation. In osteoarthritis, nerve growth and sensitisation may alter responses to loading and inflammatory signals. This does not make cartilage changes irrelevant: they can affect load distribution and nearby tissues.", "Studies associate subchondral bone marrow changes and inflammation of the joint lining with knee pain. One longitudinal study linked changes in synovitis with changes in pain; another associated enlarging bone marrow lesions with new symptoms. The strength of these relationships differs between studies and populations."]),
 ("Why can't MRI give a complete answer?", ["MRI describes structure, not a person's pain experience. In a BMJ study of adults over 50 with normal osteoarthritis X-rays, cartilage changes were common even without pain. A six-year study of knees without radiographic osteoarthritis found some statistical links between MRI findings and pain, but no single finding corresponded to a clinically important difference. It would be too simple to call one MRI feature the cause for every patient.", "The video's point that normal cartilage itself lacks sensory innervation is well founded. Its suggestion that one MRI feature is universally the strongest marker of pain is too categorical. The type of symptom, stage, other tissues and individual pain sensitivity matter."]),
 ("What does this mean for care?", ["You do not need to 'fix the scan' before symptoms can improve. Explore when pain occurs, provoking activities, swelling, function and personal goals. For typical osteoarthritis, education, adapted activity and strengthening are central. A major acute change, injury or atypical symptoms call for reassessment.", "A clear account of what images can and cannot show can avoid both false reassurance and needless alarm. Pain remains real even when a scan looks relatively unremarkable."])], box="I take pain seriously without treating one MRI observation as a certain explanation. Together we connect symptoms, examination and any imaging to a practical functional goal.")),
 dict(key="injection", video="bYbtlsQoiQk", no_slug="kneinjeksjon-menisk-og-smertested", en_slug="knee-injections-meniscus-and-pain-source", image=23,
 no=dict(title="Kneinjeksjoner og menisksmerter – treffer vi riktig problem?", desc="En injeksjon kan plasseres presist uten at diagnosen er sikker. Hva vet vi om leddinjeksjon og målrettet injeksjon rundt menisken?", alt="Illustrasjon av klinisk undersøkelse av kne med fremhevet menisk", tags=["Kne", "Injeksjon", "Menisk", "Ultralyd"], intro="Hvis en kneinjeksjon ikke hjelper, betyr det ikke automatisk at nålen traff feil. Den kan ha nådd leddrommet, men behandlingen kan ha vært lite relevant for smertemekanismen – eller effekten kan ha vært kortvarig. Derfor kommer diagnosen før prosedyren.", sections=[
 ("Presis plassering er ikke det samme som riktig behandling", ["Ultralydveiledning gjør plassering av en injeksjon i kneleddet mer presis enn kun anatomiske landemerker i gjennomsnitt. Det viser at teknikken kan forbedres, ikke at hver pasient vil få langvarig smertelindring. Knesmerter kan henge sammen med leddhinne, bein under brusken, menisk, sener eller andre strukturer.", "Ved kneartrose anbefaler NICE grunnbehandling og vurderer kortison i leddet når annen medikamentell behandling er uegnet eller utilstrekkelig, eller for å støtte terapeutisk trening. Pasienten bør få vite at lindringen typisk er kortvarig, anslått til 2–10 uker. Hyppige gjentatte kortisoninjeksjoner er ikke en opplagt løsning: i en toårig randomisert studie ga injeksjon hver tredje måned mer brusktap enn saltvann og ingen signifikant smertefordel."]),
 ("Hva med injeksjon ved menisken?", ["Videoen fremhever smerter fra vev rundt meniskkanten og foreslår en liten, ultralydveiledet injeksjon der. Det finnes en liten kasusserie med 32 personer med kneartrose og menisk som hadde glidd utover, samt en anatomisk gjennomførbarhetsstudie. De viser at metoden kan utføres og at noen rapporterte kortvarig bedring. Uten gode sammenligningsgrupper kan vi ikke si at den er bedre enn en vanlig leddinjeksjon, trening eller naturlig bedring.", "Menisken kan være endret på MR uten å være den viktigste årsaken til symptomene. Ved degenerative meniskrifter fant en femårig randomisert studie at treningsterapi ikke var dårligere enn artroskopisk delvis meniskfjerning for pasientrapportert funksjon. En lokal injeksjon reparerer ikke en strukturell meniskskade og er ikke en erstatning for vurdering av låsning, traume eller betydelig funksjonstap."]),
 ("En beslutning sammen med pasienten", ["Før en injeksjon bør man avklare målet: kortvarig lindring for å komme i gang med aktivitet, eller behandling av en annen konkret tilstand? Smerteplassering alene identifiserer ikke sikkert hvilket vev som gir symptomer. Det er viktig å drøfte mulig gevinst, risiko, usikkerhet og alternativene, og avtale hvordan funksjon og effekt skal følges opp."])], box="Jeg begynner med sykehistorie og undersøkelse. Dersom injeksjon er aktuelt, bruker jeg presisjon som et middel – ikke som bevis for diagnosen – og legger samtidig en plan for aktivitet og oppfølging."),
 en=dict(title="Knee Injections and Meniscal Pain – Are We Addressing the Right Problem?", desc="An accurately placed injection does not prove a diagnosis. What do we know about joint injections and injections around the meniscus?", alt="Illustration of a knee examination with the meniscus highlighted", tags=["Knee", "Injection", "Meniscus", "Ultrasound"], intro="When a knee injection does not help, it does not necessarily mean the needle missed. The medication may have reached the joint, while the treatment was not well matched to the pain mechanism – or any effect was brief. Diagnosis comes before procedure.", sections=[
 ("Accurate placement is not the same as the right treatment", ["Ultrasound guidance improves the average accuracy of intra-articular knee injections compared with landmarks alone. That tells us about technique, not that every patient will experience lasting pain relief. Knee symptoms may involve the synovium, subchondral bone, meniscus, tendons or other tissues.", "For knee osteoarthritis, NICE prioritises core care and suggests considering intra-articular corticosteroid when other medicines are unsuitable or ineffective, or to support therapeutic exercise. People should be told relief is usually short term, around 2–10 weeks. Repeated frequent injections are not an obvious solution: in a two-year randomised trial, injections every three months caused more cartilage loss than saline without a significant pain advantage."]),
 ("What about an injection around the meniscus?", ["The video draws attention to tissue near the meniscal edge and proposes a small ultrasound-guided injection there. A case series of 32 people with knee osteoarthritis and meniscal extrusion, and an anatomical feasibility study, show that the approach can be performed and some patients reported short-term improvement. Without robust comparison groups, they cannot show it works better than a joint injection, exercise or natural recovery.", "Meniscal changes on MRI need not be the main driver of symptoms. In a five-year randomised trial of degenerative tears, exercise-based physical therapy was non-inferior to arthroscopic partial meniscectomy for patient-reported function. A local injection does not repair a structural tear and does not replace assessment of locking, injury or major functional loss."]),
 ("Making a shared decision", ["Before injection, clarify the goal: short-term relief to enable movement, or treatment of another defined condition? Pain location alone cannot reliably identify the responsible tissue. Discuss potential benefit, risks, uncertainty and alternatives, then agree how function and response will be reviewed."])], box="I begin with the history and examination. If injection is appropriate, precision is a means, not proof of the diagnosis; activity and follow-up remain part of the plan.")),
 dict(key="sitting", video="j3vsGf4bPaw", no_slug="setesmerter-nar-du-sitter", en_slug="buttock-pain-when-sitting", image=24,
 no=dict(title="Setesmerter når du sitter – hvorfor er ikke MR alene nok?", desc="Sittesmerter i setet kan komme fra flere strukturer. Smertested, belastning og undersøkelse gir mer mening sammen enn et MR-funn alene.", alt="Illustrasjon av en sittende person med markert trykk ved setet", tags=["Setesmerter", "Sitting", "Hamstrings", "Diagnostikk"], intro="Smerter i setet ved sitting kan oppleves som et lite, presist punkt – eller som et større område med utstråling. Begge deler er reelt, men ingen av mønstrene gir én sikker diagnose. Vi må finne ut hva som faktisk provoserer, lindrer og eventuelt gir nervesymptomer.", sections=[
 ("Flere mulige forklaringer", ["Smerte nær sitteknuten, særlig ved lang sitting og løping, kan passe med irritasjon i den øvre hamstringsenen. Dyp setesmerte med utstråling kan i enkelte tilfeller skyldes irritasjon av isjiasnerven i det dype seterommet. Smerter på utsiden av hoften kan i stedet dreie seg om gluteal tendinopati. Rygg og hofteledd kan også gi smerte i samme region.", "Disse tilstandene overlapper. En systematisk oversikt over dyp setesyndrom beskriver sykehistorie, kliniske tester og ved behov bildediagnostikk som del av vurderingen. En annen oversikt viser at smerte som øker ved sitting også er beskrevet ved piriformis-relaterte plager. Derfor blir det feil å avvise alle muskel- og seneårsaker på forhånd."]),
 ("MR-funn må kobles til plagene", ["I en MR-studie av øvre hamstringsene var økt signal inne i senen svært vanlig og ikke knyttet til symptomer alene; enkelte andre vevsforandringer var oftere forbundet med plager, men kunne også forekomme hos symptomfrie. Et bilde kan hjelpe når det svarer på et klinisk spørsmål, men er ikke en «smertedetektor».", "Undersøkelsen bør kartlegge nøyaktig hvor det gjør vondt, om sitting, gange, løping eller hoftebevegelser endrer smerten, samt kraft, følelse og eventuelle ryggsymptomer. Ved nye lammelser, endret blære-/tarmfunksjon eller andre alvorlige nevrologiske symptomer trengs rask medisinsk vurdering."]),
 ("Vær varsom med bastante smerteskalaer", ["Videoen foreslår at en skår på 3 av 10 ikke er «ekte smerte», mens 7 eller mer peker mot bestemte vev. Dette støttes ikke av forskning. Skalaen beskriver intensitet slik pasienten opplever den; den kan ikke fortelle om smerten kommer fra nerve, bein, sene eller muskel. Studier finner dessuten at grenser mellom mild, moderat og alvorlig smerte varierer.", "Tilpasset belastning og gradvis trening kan være nyttig når riktig tilstand er identifisert. Ved gluteal tendinopati ga veiledning og trening bedre global bedring enn kortisoninjeksjon ved lang oppfølging i en randomisert studie. Det betyr ikke at ett treningsprogram passer alle som får vondt av å sitte – eller at tøyning automatisk fører til varig skade."])], box="Jeg bruker smertens plassering som et spor, ikke en fasit. Sykehistorie, målrettede tester og eventuelle bilder settes sammen til en forklaring som også gir mening for pasienten."),
 en=dict(title="Buttock Pain When Sitting – Why MRI Alone Is Not Enough", desc="Sitting-related buttock pain can have several causes. Location, loading and examination matter more together than an isolated MRI finding.", alt="Illustration of a seated person showing pressure at the buttock", tags=["Buttock pain", "Sitting", "Hamstrings", "Diagnosis"], intro="Sitting-related buttock pain may feel like one precise point or spread across a larger area. Both experiences are real, but neither pattern gives a certain diagnosis. We need to understand what provokes and eases it, and whether nerve symptoms are present.", sections=[
 ("Several possible explanations", ["Pain near the sitting bone, particularly with prolonged sitting and running, may be consistent with proximal hamstring tendinopathy. Deep buttock pain with radiation can sometimes reflect sciatic nerve irritation in the deep gluteal space. Pain on the outside of the hip may instead involve the gluteal tendons. The back and hip joint can also refer pain to the region.", "These presentations overlap. A systematic review of deep gluteal syndrome describes history, examination and imaging when indicated as parts of the assessment. Another review found sitting pain among the features reported in piriformis-related presentations. It would therefore be wrong to rule out all muscular or tendon causes in advance."]),
 ("Connect MRI findings with symptoms", ["In a study of proximal hamstring MRI, increased signal within the tendon was very common and by itself unrelated to symptoms. Some other findings were associated with symptoms more often, yet could still appear without pain. Imaging can help answer a clinical question; it is not a pain detector.", "Assessment should establish the exact location, effects of sitting, walking, running and hip movement, and any changes in strength, sensation or back symptoms. New paralysis, changes in bladder or bowel control, or other serious neurological features warrant prompt medical assessment."]),
 ("A pain score cannot identify the tissue", ["The video suggests that 3 out of 10 is not 'real pain', whereas 7 or above points to particular tissues. Research does not support that. A numerical rating describes the person's experienced intensity; it does not distinguish nerve, bone, tendon or muscle pain. Studies also find that boundaries between mild, moderate and severe pain vary.", "Adjusted loading and progressive exercise may help when the condition has been properly assessed. In gluteal tendinopathy, education and exercise led to better global improvement than corticosteroid injection at longer follow-up in a randomised trial. That does not mean one exercise plan suits everyone with sitting pain, or that stretching inevitably causes permanent damage."])], box="I use the location of pain as a clue, not a verdict. History, focused tests and any appropriate imaging need to form an explanation that makes sense to the patient."))
]

SOURCE = (ROOT / "normalt-rontgenbilde-knesmerter.html").read_text()
EN_SOURCE = (ROOT / "en/normal-knee-xray-persistent-pain.html").read_text()

def esc(text):
    return html.escape(str(text), quote=True)

def render(a, lang):
    english = lang == "en"
    d = a[lang]
    slug = a["en_slug"] if english else a["no_slug"]
    other_slug = a["no_slug"] if english else a["en_slug"]
    url = BASE + ("en/" if english else "") + slug + ".html"
    other_url = BASE + ("" if english else "en/") + other_slug + ".html"
    image = BASE + "images/web/aktuelt-" + str(a["image"]) + ".jpg"
    template = EN_SOURCE if english else SOURCE
    header = re.search(r'<header class="site-header".*?</header>', template, re.S).group()
    footer = re.search(r'<footer class="site-footer".*?</footer>', template, re.S).group()
    if english:
        header = header.replace("../normalt-rontgenbilde-knesmerter.html", "../" + other_slug + ".html")
    else:
        header = header.replace("en/normal-knee-xray-persistent-pain.html", "en/" + other_slug + ".html")
    sections = "\n".join('<h2 style="font-size:1.3rem;font-weight:800;color:var(--navy);margin:2.2rem 0 1rem;">'+esc(heading)+'</h2>\n'+"\n".join('<p style="color:var(--muted);line-height:1.7;margin-bottom:1rem;">'+esc(p)+'</p>' for p in paras) for heading, paras in d["sections"])
    source_list = ['<li style="margin-bottom:.6rem;">'+('Video – utgangspunkt for artikkelen: ' if not english else 'Video – starting point for this article: ')+'<a href="https://www.youtube.com/watch?v='+a["video"]+'" target="_blank" rel="noopener">YouTube</a>. '+('Påstander kontrollert mot forskningen under.' if not english else 'Claims checked against the research below.')+'</li>']
    for author, title, journal, year, identifier in REFS[a["key"]]:
        link = 'https://pubmed.ncbi.nlm.nih.gov/'+str(identifier)+'/' if isinstance(identifier, int) else identifier
        source_list.append('<li style="margin-bottom:.6rem;">'+esc(author)+' «'+esc(title)+'». <em>'+esc(journal)+'</em>. '+str(year)+'. <a href="'+esc(link)+'" target="_blank" rel="noopener">'+('Kilde' if not english else 'Source')+'</a>.</li>')
    chips = "".join('<li style="background:var(--pale-blue);color:var(--navy);font-size:.82rem;font-weight:600;padding:.35rem .8rem;border-radius:999px;list-style:none;">'+esc(t)+'</li>' for t in d["tags"])
    graph = {"@context":"https://schema.org","@graph":[{"@type":"MedicalBusiness","@id":BASE+"#klinikk","name":"Stavros Litsos – "+("Manual Therapist" if english else "Manuellterapeut"),"url":BASE,"image":BASE+"images/web/share.jpg","medicalSpecialty":"PhysicalTherapy","founder":{"@id":BASE+"#stavros"}},{"@type":"Person","@id":BASE+"#stavros","name":"Stavros Litsos","jobTitle":"Lead manual therapist" if english else "Fagansvarlig manuellterapeut","url":BASE},{"@type":"Article","@id":url+"#article","headline":d["title"],"description":d["desc"],"inLanguage":"en-GB" if english else "nb-NO","keywords":", ".join(d["tags"]),"image":image,"datePublished":DATE,"dateModified":DATE,"author":{"@id":BASE+"#stavros"},"publisher":{"@id":BASE+"#klinikk"},"mainEntityOfPage":url}]}
    graph_json = json.dumps(graph, ensure_ascii=False, separators=(',', ':')).replace('</', '<\\/')
    local_css = "../style.css?v=7" if english else "style.css?v=7"
    service = "tjenester.html"; booking = "booking.html"
    return f'''<!DOCTYPE html>
<html lang="{'en' if english else 'no'}"><head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><meta name="robots" content="noindex, nofollow">
<title>{esc(d['title'])} | Stavros Litsos</title><meta name="description" content="{esc(d['desc'])}"><link rel="canonical" href="{url}">
<meta property="og:type" content="article"><meta property="og:site_name" content="Stavros Litsos"><meta property="og:title" content="{esc(d['title'])}"><meta property="og:description" content="{esc(d['desc'])}"><meta property="og:url" content="{url}"><meta property="og:locale" content="{'en_GB' if english else 'nb_NO'}"><meta property="og:image" content="{image}"><meta property="og:image:width" content="1400"><meta property="og:image:height" content="933"><meta property="og:image:alt" content="{esc(d['alt'])}">
<meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="{esc(d['title'])}"><meta name="twitter:description" content="{esc(d['desc'])}"><meta name="twitter:image" content="{image}">
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Archivo:wght@500;700;800;900&family=Inter:wght@400;500;600&display=swap" rel="stylesheet">
<link rel="alternate" hreflang="no" href="{BASE+a['no_slug']+'.html'}"><link rel="alternate" hreflang="en" href="{BASE+'en/'+a['en_slug']+'.html'}"><link rel="alternate" hreflang="x-default" href="{BASE+a['no_slug']+'.html'}"><link rel="stylesheet" href="{local_css}">
<script type="application/ld+json">{graph_json}</script></head><body>
{header}
<main><div class="page-header"><div class="section-inner"><p class="eyebrow">{'Clinical insights' if english else 'Fagstoff'}</p><h1>{esc(d['title'])}</h1></div></div>
<section class="section"><div class="section-inner narrow"><p class="lede" style="font-size:1.1rem;font-weight:600;color:var(--navy);margin-bottom:1.4rem;">{esc(d['intro'])}</p>
{sections}
<div style="border-left:4px solid var(--navy);padding:1.5rem 1.7rem;background:var(--pale-blue);border-radius:6px;margin:2rem 0;"><h2 style="font-size:1.15rem;font-weight:800;color:var(--navy);margin-bottom:.75rem;">{'How I approach it' if english else 'Slik jobber jeg'}</h2><p style="color:var(--muted);line-height:1.7;margin:0;">{esc(d['box'])}</p></div>
<div class="cta-row"><a href="{service}" class="text-link">{'Explore services' if english else 'Se tjenester'} <span class="arrow">➔</span></a><a href="{booking}" class="btn btn-pill" style="background:var(--navy);color:var(--text-on-dark);">{'Book an appointment' if english else 'Book time'} <span class="arrow">➔</span></a></div>
<details class="article-sources"><summary>{'Sources' if english else 'Kilder'}</summary><ol style="color:var(--muted);line-height:1.7;font-size:.93rem;margin:0 0 2rem 1.1rem;padding:0;">{''.join(source_list)}</ol></details>
<div style="border-top:1px solid var(--pale-blue-2);padding-top:1.4rem;margin-bottom:2rem;"><h2 style="font-size:.78rem;font-weight:700;color:var(--muted);letter-spacing:.08em;text-transform:uppercase;margin-bottom:.8rem;">{'Topics' if english else 'Emneord'}</h2><ul style="display:flex;flex-wrap:wrap;gap:.5rem;margin:0;padding:0;">{chips}</ul></div>
</div></section></main>
{footer}
<script src="{'../' if english else ''}script.js"></script><script defer type="module" src="https://static.cloudflareinsights.com/beacon.min.js" data-cf-beacon='{{"token":"4fc965783a5c42aa9813d2b59a4ca00d"}}'></script></body></html>
'''

if __name__ == '__main__':
    for article in ARTICLES:
        for language in ('no', 'en'):
            path = ROOT / ('en/' if language == 'en' else '') / (article[language+'_slug'] + '.html')
            if path.exists():
                raise SystemExit(f'Refusing to overwrite existing file: {path}')
            path.write_text(render(article, language), encoding='utf-8')
            print(path.relative_to(ROOT))
